Unsupported AFT operation type is not fatal enough to drop the connection
openconfig/gribigo pull request #134
Opened 2022-03-30 06:21 UTC by xw-g

Propose to maintain the connection in the case of unsupported AFT operations. If use case demands, maybe we can later consider adding a new [AFTResult.Status](https://github.com/openconfig/gribi/blob/7d876062a31f072bd5b9159b522120ef3fdb5f44/v1/proto/service/gribi.proto#L242) for the client to action upon.

2022-04-08 20:23 UTC, robshakir requested changes
LGTM - is there test coverage that needs to be updated here? (If not, please can we add it?)

2022-04-11 20:42 UTC, xw-g commented
ack, I'll check the test coverage later. Thanks!

2022-04-22 21:17 UTC, xw-g commented
Test coverage added. @robshakir

2022-04-22 21:20 UTC, robshakir approved these changes
Thanks, LGTM!

2022-04-29 19:49 UTC, merged